-- Общая структура БД.

-- Создание схемы команды FF_Hack для проекта согласования календаря встреч.
CREATE SCHEMA IF NOT EXISTS ff_hack_schema AUTHORIZATION "cnrprod1722884901-team-74157";
COMMENT ON SCHEMA ff_hack_schema IS 'Схема команды FF_Hack для проекта согласования календаря встреч.';

-- Создание сущности должностей предприятия.
CREATE TABLE IF NOT EXISTS ff_hack_schema.ff_hack_positions
(
	-- Идентификатор должности.
    id_position 			INTEGER
							NOT NULL
							CONSTRAINT ff_hack_positions_pkey PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
							(
								INCREMENT 1
								START 0
								MINVALUE 0
								CACHE 1
							),
	-- Наименование должности.
    name_position 			VARCHAR(256)
							NOT NULL
                            UNIQUE,
	-- Описание должности.
    description_position 	TEXT
);

-- Назначение владельцем сущности должностей роли cnrprod1722884901-team-74157.
ALTER TABLE IF EXISTS ff_hack_schema.ff_hack_positions OWNER to "cnrprod1722884901-team-74157";

-- Создание сущности ролей сотрудников.
CREATE TABLE IF NOT EXISTS ff_hack_schema.ff_hack_roles
(
	-- Идентификатор роли.
    id_role 	INTEGER
				NOT NULL
				CONSTRAINT ff_hack_roles_pkey PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
				(
					INCREMENT 1
					START 0
					MINVALUE 0
					CACHE 1
				),
	-- Наименование роли.
    name_role	VARCHAR(30)
				NOT NULL
                UNIQUE
);

-- Назначение владельцем сущности ролей роли cnrprod1722884901-team-74157.
ALTER TABLE IF EXISTS ff_hack_schema.ff_hack_roles OWNER to "cnrprod1722884901-team-74157";

-- Создание сущности сотрудников.
CREATE TABLE IF NOT EXISTS ff_hack_schema.ff_hack_employees
(
	-- Логин сотрудника.
    login_employee				VARCHAR(30)
								NOT NULL
								CONSTRAINT ff_hack_employees_pkey PRIMARY KEY,
	-- Пароль сотрудника (предполагается SHA256).
    password_employee			VARCHAR(256)
								NOT NULL,
	-- Фамилия сотрудника.
    last_name_employee			VARCHAR(30)
								NOT NULL,
	-- Имя сотрудника.
    first_name_employee			VARCHAR(20)
								NOT NULL,
	-- Отчество сотрудника.
    patronymic_name_employee	VARCHAR(20),
	-- Электронная почта сотрудника.
    email_employee				VARCHAR(40)
								NOT NULL
                                UNIQUE,
	-- Телефон сотрудника.
    phone_employee				VARCHAR(20)
								NOT NULL
                                UNIQUE,
	-- Идентификатор должности сотрудника.
    id_position_employee		INTEGER
								NOT NULL,
	-- Идентификатор роли сотрудника.
    id_role_employee			INTEGER
								NOT NULL,
    CONSTRAINT ff_hack_employees_positions_fkey FOREIGN KEY (id_position_employee)
        REFERENCES ff_hack_schema.ff_hack_positions (id_position),
    CONSTRAINT ff_hack_employees_roles_fkey FOREIGN KEY (id_role_employee)
        REFERENCES ff_hack_schema.ff_hack_roles (id_role)
);

-- Назначение владельцем сущности сотрудников роли cnrprod1722884901-team-74157.
ALTER TABLE IF EXISTS ff_hack_schema.ff_hack_employees OWNER to "cnrprod1722884901-team-74157";

-- Создание сущности клиентов (кандидатов).
CREATE TABLE IF NOT EXISTS ff_hack_schema.ff_hack_candidates
(
	-- Логин кандидата.
    login_candidate				VARCHAR(30)
								NOT NULL
								CONSTRAINT ff_hack_candidates_pkey PRIMARY KEY,
	-- Пароль кандидата (предполагается SHA256).
    password_candidate			VARCHAR(256)
								NOT NULL,
	-- Фамилия кандидата.
    last_name_candidate			VARCHAR(30)
								NOT NULL,
	-- Имя кандидата.
    first_name_candidate		VARCHAR(20)
								NOT NULL,
	-- Отчество кандидата.
    patronymic_name_candidate	VARCHAR(20),
	-- Электронная почта кандидата.
    email_candidate				VARCHAR(40)
								NOT NULL
                                UNIQUE,
	-- Телефон кандидата.
    phone_candidate				VARCHAR(20)
								NOT NULL
                                UNIQUE
);

-- Назначение владельцем сущности сотрудников роли cnrprod1722884901-team-74157.
ALTER TABLE IF EXISTS ff_hack_schema.ff_hack_employees OWNER to "cnrprod1722884901-team-74157";

-- Создание сущности конференций (встреч).
CREATE TABLE IF NOT EXISTS ff_hack_schema.ff_hack_conferences
(
	-- Идентификатор конференции.
    id_conference 			INTEGER
							NOT NULL
							CONSTRAINT ff_hack_conferences_pkey PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
							(
								INCREMENT 1
								START 0
								MINVALUE 0
								CACHE 1
							),
	-- Наименование конференции.
    name_conference 		VARCHAR(256)
							NOT NULL,
	-- Описание конференции.
    description_conference 	TEXT
);

-- Назначение владельцем сущности конференций роли cnrprod1722884901-team-74157.
ALTER TABLE IF EXISTS ff_hack_schema.ff_hack_conferences OWNER to "cnrprod1722884901-team-74157";

-- Создание сущности статусов конференций (встреч).
CREATE TABLE IF NOT EXISTS ff_hack_schema.ff_hack_statuses
(
	-- Идентификатор статуса конференции.
    id_status	INTEGER
				NOT NULL
				CONSTRAINT ff_hack_statuses_pkey PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
				(
					INCREMENT 1
					START 0
					MINVALUE 0
					CACHE 1
				),
	-- Наименование статуса конференции.
    name_status	VARCHAR(30)
				NOT NULL
);

-- Назначение владельцем сущности конференций роли cnrprod1722884901-team-74157.
ALTER TABLE IF EXISTS ff_hack_schema.ff_hack_statuses OWNER to "cnrprod1722884901-team-74157";

-- Создание сущности брифингов.
CREATE TABLE IF NOT EXISTS ff_hack_schema.ff_hack_briefings
(
	-- Идентификатор брифинга.
	id_briefing 				INTEGER
								NOT NULL
								CONSTRAINT ff_hack_briefings_pkey PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
								(
									INCREMENT 1
									START 0
									MINVALUE 0
									CACHE 1
								),
	-- Наименование брифинга.
    name_briefing 				VARCHAR(256)
								NOT NULL,
	-- Тип конференции (встречи).
	id_conference_briefing		INTEGER
								NOT NULL,
	-- Логин эксперта.
    login_expert				VARCHAR(30)
								NOT NULL,
	-- Идентификатор кандидата.
	login_candidate				VARCHAR(30)
								NOT NULL,
	id_position_candidate		INTEGER
								NOT NULL,
	-- Логин рекрутера (HR).
    login_recruiter				VARCHAR(30)
								NOT NULL,
	date_briefing				DATE
								NOT NULL,
	time_briefing				TIME
								NOT NULL,
	id_status_briefing				INTEGER
								NOT NULL,
	CONSTRAINT ff_hack_briefings_conferences_fkey FOREIGN KEY (id_conference_briefing)
        REFERENCES ff_hack_schema.ff_hack_conferences (id_conference),
    CONSTRAINT ff_hack_briefings_employees_expert_fkey FOREIGN KEY (login_expert)
        REFERENCES ff_hack_schema.ff_hack_employees (login_employee),
	CONSTRAINT ff_hack_briefings_candidates_fkey FOREIGN KEY (login_candidate)
        REFERENCES ff_hack_schema.ff_hack_candidates (login_candidate),
	CONSTRAINT ff_hack_briefings_positions_fkey FOREIGN KEY (id_position_candidate)
		REFERENCES ff_hack_schema.ff_hack_positions (id_position),
	CONSTRAINT ff_hack_briefings_employees_recruiter_fkey FOREIGN KEY (login_recruiter)
        REFERENCES ff_hack_schema.ff_hack_employees (login_employee),
	CONSTRAINT ff_hack_briefings_statuses_fkey FOREIGN KEY (id_status_briefing)
        REFERENCES ff_hack_schema.ff_hack_statuses (id_status)
);

-- Назначение владельцем сущности конференций роли cnrprod1722884901-team-74157.
ALTER TABLE IF EXISTS ff_hack_schema.ff_hack_briefings OWNER to "cnrprod1722884901-team-74157";